# Change these first
owner: rainzee # Your GitHub organization or username, where this repository lives
repo: RiotSkin4CN-Status # The name of this repository

sites:
  - name: RiotSkin4CN-API
    url: https://riotskin4cn.deta.dev/v1/public
  - name: RiotSkin4CN-Download
    url: https://s-cd-4307-general.oss.dogecdn.com/riotskin4cn/live.json

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /RiotSkin4CN-Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: RiotSkin4CN 系统状态
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: RiotSkin4CN 系统状态监控
  navbar:
    - title: 下载客户端
      href: https://s-cd-4307-general.oss.dogecdn.com/riotskin4cn/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
